server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  preferIpAddress: true
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bikes/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: "http://localhost:9090/realms/gage-realm/protocol/openid-connect/auth"
            userinfo-uri: "http://localhost:9090/realms/gage-realm/protocol/openid-connect/userinfo"
            user-name-attribute: preferred_username
            token-uri: "http://localhost:9090/realms/gage-realm/protocol/openid-connect/token"
        registration:
          gage-client:
            provider: keycloak
            client-id: gage-client
            client-secret: pcYK2ZuBEeCGHGwSqRys0UjcZYZsaZFI
            authorization-grant-type: "authorization_code"
            redirect-uri: "{baseUrl}/login/oauth2/code/gage-client"


