server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/luegmy/microservice-tutorial-gage
          search-paths: config-data
  application:
    name: config-service
